### ISSUE TITLE
binary-zip missing PIL module

### ISSUE THREAD

**Issue by chinmaya-dehury** [radon-h2020/tosca-blueprint-aws-lambda#1]
I am able to successfully deploy the lambda function using xopera. 
However, I got the following error while testing the lambda function.
Error screenshot [here](https://drive.google.com/open?id=1kfJbcp_wnMz7rG8T9Zhr4-7mbtA0cSUD).

**Comment by naesheim** [comment]
@chinmaya-dehury  is this resolved?

**Comment by chinmaya-dehury** [comment]
Yes...the error can be handled if you build the binary-zip from the scratch (using the [steps](https://github.com/radon-h2020/FaaS-thumbnail-generator-python)) instead of using the given binary-zip file.
